
export const SET_USERINFO = 'SET_USERINFO'
export const SET_INPARTCOUNT = 'SET_INPARTCOUNT'
export const SET_OUTPARTCOUNT = 'SET_OUTPARTCOUNT'
export const SET_INPARTFORM = 'SET_INPARTFORM'
export const SET_OUTPARTFORM = 'SET_OUTPARTFORM'
export const SET_EDITITEM = 'SET_EDITITEM'